### ISSUE TITLE
MarketoSDK-Cannot connect to Marketo.

### ISSUE THREAD

**Issue by mud18** [Marketo/ios-sdk#21]
Hi,

We are trying to integrate Marketo SDK in iOS & Android app. After following the documentation from Marketo team - https://docs.marketo.com/display/public/DOCS/Add+a+Mobile+App 

We have added all the necessary code in our mobile apps with the generated - `Munchkin Account Id` & `Secret Key`. But we are still facing issues and can see these error logs -

```
MarketoSDK-Cannot connect to Marketo.
MarketoFramework--[MKTEventLogger reportEvents:] [Line 153] Marketo is not initlized
```
After looking for the issue we landed up on below mentioned link -
https://github.com/Marketo/ios-sdk/issues/18

Which seems to have similar case as ours. We are also trying to integrated Marketo in our apps for the first time.

Could you please help us with the issue.

Thanks

**Comment by mbijapur** [comment]
Hi @mud18, thanks for reaching out, seems like your subscription is not yet provisioned for Mobile Integration. Can you please reach out to your Marketo account manager for the same? Or else please let us know your munchkin id, so that we can get the process initiated.
Thanks

**Comment by mud18** [comment]
Hi @mbijapur ,
I tried reaching out to Marketo team via our account manager and they are saying that Mobile facility is provisioned and enabled in our account however I keep getting above error.
Here is my Munchkin Id -> 822-DNR-415

Thanks

**Comment by skharemarketo** [comment]
Thanks @mud18 for sharing munchkin id, this helped us to identify the problem. Looks like provisioning is not fully completed, which is why your app stills shows as Not Integrated at Admin. I'll reach out to our Support Manager to take this up on priority and handled correctly by account manager. Sorry for the inconvenience.

**Comment by mud18** [comment]
Thanks for looking into this @skharemarketo Please let me know in case you need more details form my end or you need me to test the integration once you are done with provisioning thing.

**Comment by skharemarketo** [comment]
Absolutely @mud18, I have reached out to concerned team here to complete the provisioning of your subscription. I'll keep you posted on the updates.

**Comment by mud18** [comment]
Hi @skharemarketo were you able to get hold of issue or any expected time by when I can again try it and see if it works.

**Comment by skharemarketo** [comment]
Hi @mud18, thank you for following up, I got update from account manager that they have started looking into remaining provisioning task and also reached out to subscription's contact person for further details. 
We really appreciate your patience and recommend you to followup through that channel.

**Comment by mud18** [comment]
Thanks @skharemarketo for taking it up, our Account Manager has also raised a ticket with Marketo. Your team is helping us and push notifications are now working. Thanks

**Comment by skharemarketo** [comment]
Thats great @mud18, we are glad that your issue is moving towards resolution!
