### ISSUE TITLE
M1 Mac / Arm64 support required

### ISSUE THREAD

**Issue by dhiraj** [Marketo/ios-sdk#23]
We're unable to build our project which relies on the Marketo-iOS-SDK on M1 Macs targeting running on Simulator. Error is: 

`ld: in /Users/username/projectpath/ios/Pods/Marketo-iOS-SDK/Marketo.framework/Marketo(Marketo.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/username/projectpath/Pods/Marketo-iOS-SDK/Marketo.framework/Marketo' for architecture arm64`

Please add support for building on new Macs!

**Comment by mbijapur** [comment]
Thanks @dhiraj for bringing this up. We are working on this & will update here once we add the support.

**Comment by dgupta-oanda** [comment]
Hello, please confirm that the latest SDK does in fact supporting building for arm64 simulator and close this issue, thanks!

**Comment by mbijapur** [comment]
Hi @dgupta-oanda - Yes, the latest SDK 0.7.8 supports for building for arm64 simulator.
