### ISSUE TITLE
Allow MarketoLead() to set MarketoID or PersonID

### ISSUE THREAD

**Issue by kaiwu28** [Marketo/ios-sdk#24]
Hi,

Currently we are able to associate a lead using email as follows:

    let profile = MarketoLead() 
    profile?.setEmail(user.email) 
    Marketo.sharedInstance()?.associateLead(profile)

But this would create a NEW PERSON activity for this user.

Are we able to add an option for us to set the Person ID so we don't misleadingly send this NEW PERSON activity type?

For example:
        let profile = MarketoLead() 
        profile?.setProfileId(user.id) 
        Marketo.sharedInstance()?.associateLead(profile)

Regards,
Kai

**Comment by mbijapur** [comment]
Hi @kaiwu28, thanks for reaching out. When you call associateLead the same lead gets updated and it gets merged as long as you're using same email.

**Comment by kaiwu28** [comment]
Hi @mbijapur 
But this would still create a NEW PERSON activity due to different PERSON IDs even they have the same emails, and some of our actions are based on NEW PERSON, associateLead doesn't fix this problem.

**Comment by mbijapur** [comment]
Hi @kaiwu28 - Can you please reach out to our support team & share few examples. We will be able to have a closer look at the issue to help you better.
