### ISSUE TITLE
Allow MarketoLead() to set MarketoID or PersonID 

### ISSUE THREAD

**Issue by kaiwu28** [Marketo/ios-sdk#25]
Hi,

Currently we are able to associate a lead using email as follows:

let profile = MarketoLead() 
profile?.setEmail(user.email) 
Marketo.sharedInstance()?.associateLead(profile)
But this would create a NEW PERSON activity for this user.

Are we able to add an option for us to set the Person ID so we don't misleadingly send this NEW PERSON activity type?

For example:
let profile = MarketoLead()
profile?.setProfileId(user.id)
Marketo.sharedInstance()?.associateLead(profile)

associateLead doesn't fix this problem due to different PERSON IDs even they have the same emails, and some of our actions are based on NEW PERSON activity type.

Regards,
Kai

**Comment by mbijapur** [comment]
Duplicate issue -  https://github.com/Marketo/ios-sdk/issues/24 (Original issue)
