### ISSUE TITLE
Cannot Initialize Marketo iOS SDK

### ISSUE THREAD

**Issue by ahnjac** [Marketo/ios-sdk#28]
Hi all, I am running into an issue of where I cannot connect to the SDK. This is our first time connecting to Marketo via iOS app, with munchkin id 824-XEX-790. I read other issues raised, saying that the provisioning profile is not set up fully? Would someone here be able to confirm as I am grabbing my ID and Key directly from the Marketo Console. We are also using Sandbox environment.

`2022-01-11 09:19:51.482249-0600 MarketoFramework--[MKTNetworkManager getDataFromEndpoint:] [Line 52] Getting data from end point https://824-XEX-790.mktomma.com/api/v1/sync/N0tNZTJzd21pam52QXpUUlN0T0k4MWt1?lst=0 2022-01-11 09:19:51.482534-0600[47632:732805] MarketoSDK-Current UUID is : 3A67E8DB-5655-4F33-BBF8-0A24DB56C3BC 2022-01-11 09:19:52.565540-0600 [47632:732805] MarketoSDK-The certificate for this server is invalid. You might be connecting to a server that is pretending to be “824-xex-790.mktomma.com” which could put your confidential information at risk. 2022-01-11 09:19:52.566026-0600 [47632:732805] MarketoFramework--[MKTEventLogger reportEvents:] [Line 153] Marketo is not initlized 2022-01-11 09:19:53.464053-0600 [47632:732404] MarketoSDK-[warning] is not initialized. Initialize Framwork using initializeWithMunchkinID:appSecret: method. 2022-01-11 09:19:53.493734-0600[47632:732860] MarketoFramework--[MKTEventLogger reportEvents:] [Line 153] Marketo is not initlized`

**Comment by mbijapur** [comment]
Hi @ahnjac 

You will have to get in touch with your Marketo executive for your account, they should be able to help you to check and enable Mobile feature on your Marketo subscription.

Thank you.
