### ISSUE TITLE
Cannot initialise SDK when turn on in-app message

### ISSUE THREAD

**Issue by Cyantou** [Marketo/ios-sdk#31]
We implement SDK and test Push notification successfully. 
However, we face with crashing after turn on In-app message program on Admin site. The crashing occur right at initial code 
`
let sharedInstance: Marketo = Marketo.sharedInstance()
            sharedInstance.initialize(withMunchkinID: Configs.MARKETO_ID, appSecret: Configs.MARKETO_SECERT_KEY, launchOptions: launchOptions)
`
Crashing log:
At **[Marketo initializeWithMunchkinID:appSecret:launchOptions:]** thread:
![Screenshot 2022-09-12 at 10 42 16](https://user-images.githubusercontent.com/113324583/189569826-abf4e769-9871-4b9e-aefe-a324b8b0f18a.png)

**Comment by mbijapur** [comment]
Hi @Cyantou - From the error it looks like App Munchkin & secret are empty? Have you verified the values?
If you still face the issue please provide values manually & verify once or please reach out to our support team to create a customer request to assist you further on this. Thanks.

**Comment by Cyantou** [comment]
> Hi @Cyantou - From the error it looks like App Munchkin & secret are empty? Have you verified the values? If you still face the issue please provide values manually & verify once or please reach out to our support team to create a customer request to assist you further on this. Thanks.

Hi @mbijapur, the crashing occurs inside initial thread from Marketo SDK. Value of App Munchkin & secret always available.

**Comment by mbijapur** [comment]
@Cyantou That is strange, I don't see this issue happen. Just verified again. I request you to please reach out to our support team to create a customer request to assist you further on this. Please share is it simulator or device, OS version, crash stack trace etc as required to assist you further. Thanks.
