### ISSUE TITLE
App cannot be run on Simulator due to lack of Apple silicon support

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [Marketo/ios-sdk#32]
On a Mac with Apple silicon, you cannot build and run an app that has Marketo integrated on the Simulator because Marketo does not support Apple silicon with the current version 0.7.8.

```
platform :ios, '13.0'

target 'Test' do
use_frameworks!

pod 'Marketo-iOS-SDK'

end
```

It'll install on the Simulator but will not open and Xcode presents this error alert:
```
Application launch for 'com.mydomain.Test' did not return a valid pid nor a launch error.
Domain: NSPOSIXErrorDomain
Code: 3
Failure Reason: No such process
User Info: {
    DVTErrorCreationDateKey = "2022-10-10 16:14:56 +0000";
    IDERunOperationFailingWorker = IDELaunchiPhoneSimulatorLauncher;
}
```

**Comment by mbijapur** [comment]
@jordanhbuiltbyhq - The issue is not related to Marketo, we're able to run on simulator of Mac with Apple Silicon. Looks like a different issue, please verify again.
Thanks.
