### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [Marketo/ios-sdk#36]
Currently Marketo-iOS-SDK doesn't fully support Apple silicon. Version 0.8.0 [excludes the arm64 architecture](https://github.com/Marketo/ios-sdk/blob/7187066a201f818f9f942ed36c473f472ed0abad/Marketo-iOS-SDK.podspec#L41) which forces the Simulator to run x86_64, which means the entire app will have to compile for x86_64. That's problematic when we have other dependencies because they (correctly) only compile for the active architecture for DEBUG mode which is arm64 on Apple silicon. To workaround that, we have to force all of our dependencies to build for both x86_64 and arm64 via ONLY_ACTIVE_ARCH = NO. With that, you may be able to run the app with Xcode not using Rosetta but the Simulator will be using Rosetta. However, if you have any dependencies installed via Swift Package Manager, it's seemingly not possible to force those to build for both architectures, and thus the app won't compile on Apple silicon.

Do you have an ETA when you'll stop excluding arm64 and fully support Apple silicon?

**Comment by cain004** [comment]
I would like to see an answer to this, as well as Swift Package Manager support. We don't use and don't want to use CocoaPods. Swift Package Manager and Apple silicon have been out for years now. The fact that this sdk doesn't support either is concerning.

**Comment by ghost** [comment]
I'm also facing the same issue with this SDK. It's really holding back our codebase because the lack of arm64 support.

**Comment by mikemike396** [comment]
We found a way to patch the static binary to run on arm64_simulators. Can't guarantee this wont have issues but seems to working good on our first pass. Its compiling and shipping events to Marketo -> https://github.com/mikemike396/MarketoMobileSDK-SPM

**Comment by mbijapur** [comment]
Thank you for reaching out to us and sorry for the inconvenience caused by this delay. Somehow arm64 support went to our backlogs. We will update here once we add support for arm64 simulators. SPM support will be taken only after our next release.

**Comment by cain004** [comment]
@mbijapur Any idea what the timeline looks like for the next 2 releases?

**Comment by jordanhbuiltbyhq** [comment]
Any updates here? (Also why close this rather than close it once it's actually completed?)

**Comment by dizruptr** [comment]
Can we get an update on this? Unbelievable that this is not even being discussed.

**Comment by mbijapur** [comment]
Sorry for the inconvenience caused due to this delay. With v0.8.2 we have added support for Apple Silicon & starting v0.8.3 you can integrate this SDK using swift package manager.

**Comment by jordanhbuiltbyhq** [comment]
Great thank you
