### ISSUE TITLE
[iOS Privacy Manifest] ITMS-91055: Invalid API reason declaration

### ISSUE THREAD

**Issue by robertogvieira** [Marketo/ios-sdk#44]
Hi team,

the app I'm working on currently uses the latest version [0.8.5](https://github.com/Marketo/ios-sdk/tree/0.8.5) which was specifically released to address _Apple's_ upcoming changes regarding privacy manifest.
Kudos for addressing such requirement early in advance.

Nevertheless, I got this warning upon uploading a new build to **App Store**:
> ITMS-91055: Invalid API reason declaration - The PrivacyInfo.xcprivacy for the “Frameworks/MarketoFramework.framework/MarketoFramework” file contains “C617.1” as the value for a NSPrivacyAccessedAPITypeReasons key instead of a valid reason code for using an API in the NSPrivacyAccessedAPICategoryUserDefaults category. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, values for NSPrivacyAccessedAPITypeReasons keys in your app’s privacy manifest must be valid reason codes for the corresponding API category. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

Considering the message above and looking at the manifest changes on version **0.8.5**, one of two things seems to have happened:
- the value "**C617.1**" was placed under the string `NSPrivacyAccessedAPICategoryUserDefaults` while it should have been placed under the string `NSPrivacyAccessedAPICategoryFileTimestamp` , instead;
- besides "**CA92.1**", the other intended value to place under `NSPrivacyAccessedAPICategoryUserDefaults` was not "**C617.1**" but another one.

Could you please confirm and address this issue in a timely manner? (i.e. prior to the **May 1, 2024** deadline)
Thank you

**Comment by mbijapur** [comment]
Hi @robertogvieira thanks. We will take necessary action & will plan a release before May 1, 2024.
