### ISSUE TITLE
Define dictionary key constants

### ISSUE THREAD

**Issue by jsorge** [Marketo/ios-sdk#5]
On MarketoActionMetaData there is an actionMetadata property, but no keys are given. In the Marketo.h file, some examples are given such as "Action Type". Please make these constants to give better documentation and avoid typos.

Example:

```
header: extern NSString *const MKTActionType;
implementation: NSString *const MKTActionType = @"Action Type";
usage: @{MKTActionType: @"Shopping"}
```

**Comment by jrudydev** [comment]
Hi jsorge,

Please follow the updated documentation link and see the section covering "Sending Custom Actions on iOS". This shows the proper way to add details to the meta data object via setter methods.

**Comment by jsorge** [comment]
Are you saying that we shouldn't use the actionMetadata dictionary property, and instead use the `-setType:`, `-setDetails:`, `-setLength:`, etc methods to define the metadata?

**Comment by jrudydev** [comment]
yes

**Comment by jsorge** [comment]
Ok. If that's the case, then please mark the method as deprecated so that we know it's best not to use it or report an issue on it. Thanks!
